version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: php:8.2-apache
    restart: always
    ports:
      - "82:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      PHP_EXTENSIONS: pdo_mysql
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mysql_data:
